### ISSUE TITLE
Add Visualization

### ISSUE THREAD

**Issue by croots** [barricklab/efmcalculator2#9]
While CSV outputs are useful, especially for other computational biologists, data visualization makes the tool more friendly to non-programmers. We should build a data visualization function so that users can at a glance see where problems are.

- [x] Visualize input DNA (blocked by #5)
- [x] Visualize SSRs (blocked by #4)
- [x] Visualize RMDs (blocked by #3 and #8)
